// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAA8O3Rw8DfE2SnxkKEjLJg72Az7jMWfo',
    appId: '1:73010787943:web:7ba2788ae25a58d7c246c2',
    messagingSenderId: '73010787943',
    projectId: 'booksstore-2d661',
    authDomain: 'booksstore-2d661.firebaseapp.com',
    storageBucket: 'booksstore-2d661.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm5U3_H5cYgcn6_3TknQUtpftc-SJXY8w',
    appId: '1:73010787943:android:3ab768a9f0f792ecc246c2',
    messagingSenderId: '73010787943',
    projectId: 'booksstore-2d661',
    storageBucket: 'booksstore-2d661.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYw1piwYGHo43CR-b3oOfQMIOi1rTwo08',
    appId: '1:73010787943:ios:6499eb78befe18bdc246c2',
    messagingSenderId: '73010787943',
    projectId: 'booksstore-2d661',
    storageBucket: 'booksstore-2d661.appspot.com',
    iosClientId: '73010787943-f92k5il3slu6l76m2h2vmau7cqj5mreq.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYw1piwYGHo43CR-b3oOfQMIOi1rTwo08',
    appId: '1:73010787943:ios:6499eb78befe18bdc246c2',
    messagingSenderId: '73010787943',
    projectId: 'booksstore-2d661',
    storageBucket: 'booksstore-2d661.appspot.com',
    iosClientId: '73010787943-f92k5il3slu6l76m2h2vmau7cqj5mreq.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
